# Generated by Django 6.0.5 on 2026-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Sotuv paytidagi tannarx (keyinroq narx o'zgarsa ham aniq foyda hisobi uchun)", max_digits=12),
        ),
    ]
