# Generated by Django 6.0.5 on 2026-05-27 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_backfill_sale_cost_at_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, help_text="User o'chirilsa ham foydalanuvchi nomi qoladi", max_length=150)),
                ('action', models.CharField(choices=[('create', 'Yaratdi'), ('update', "O'zgartirdi"), ('delete', "O'chirdi"), ('login', 'Kirdi'), ('logout', 'Chiqdi'), ('login_failed', 'Kirish urinishi (xato)')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_repr', models.CharField(blank=True, help_text="Qaysi obyekt: masalan 'Sale: OYO-0001 — 3 dona'", max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": ["old", "new"], ...}')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='inventory_a_model_n_740003_idx'), models.Index(fields=['user', '-created_at'], name='inventory_a_user_id_922dec_idx')],
            },
        ),
    ]
