# Generated by Django 6.0.5 on 2026-05-27 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, help_text="Sabab: nuqson, kichik o'lcham, mijoz fikri o'zgardi...", max_length=200)),
                ('refunded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('refunded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='inventory.sale')),
            ],
            options={
                'verbose_name': 'Qaytarilish',
                'verbose_name_plural': 'Qaytarilishlar',
                'ordering': ['-refunded_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('mixed', 'Aralash')], default='cash', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.branch')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuv chek',
                'verbose_name_plural': 'Sotuv cheklari',
                'ordering': ['-sold_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text="Bitta chekka tegishli sotuvlar guruhi. Eski sotuvlar uchun bo'sh.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.saletransaction'),
        ),
    ]
