# Generated by Django 6.0.5 on 2026-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_return_saletransaction_sale_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='fiscal_module_id',
            field=models.CharField(blank=True, help_text='Filialning kassa apparati ID (OFD beradi)', max_length=80),
        ),
        migrations.AddField(
            model_name='branch',
            name='inn',
            field=models.CharField(blank=True, help_text='STIR / INN (Soliq fiskalizatsiyasi uchun). Yuridik shaxs uchun 9 raqam, jismoniy shaxs uchun 14.', max_length=14),
        ),
        migrations.AddField(
            model_name='product',
            name='mxik_code',
            field=models.CharField(blank=True, help_text='Mahsulot xizmat international klassifikator kodi (soliq.uz)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='package_code',
            field=models.CharField(blank=True, help_text="Markirovka kodi (zarur tovarlar uchun; aks holda bo'sh)", max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_code',
            field=models.CharField(blank=True, default='796', help_text='Birlik kodi (OKEI). 796 = dona, 166 = kg, 778 = juft.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=12, help_text="QQS foizi. UZ standart: 12%, ba'zi tovarlar uchun 0% yoki 15%.", max_digits=5),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='customer_inn',
            field=models.CharField(blank=True, help_text='B2B sotuvlar uchun mijozning STIRi (e-faktura beriladi)', max_length=14),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='fiscal_error',
            field=models.TextField(blank=True, help_text="Yuborish muvaffaqiyatsiz bo'lgan bo'lsa, xatolik matni"),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='fiscal_qr_url',
            field=models.URLField(blank=True, help_text="OFD bergan QR kod URL'i — chekka chiqaramiz, mijoz tekshirishi uchun"),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='fiscal_receipt_number',
            field=models.CharField(blank=True, help_text='OFD bergan fiskal chek raqami (provider qaytaradi)', max_length=80),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='fiscal_status',
            field=models.CharField(blank=True, choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborilgan'), ('failed', 'Xatolik'), ('skipped', "O'tkazib yuborildi")], help_text="OFD'ga yuborish holati", max_length=20),
        ),
    ]
