# Generated by Django 6.0.5 on 2026-06-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_branch_fiscal_module_id_branch_inn_product_mxik_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, help_text='Vergul bilan: VIP, doimiy, optom...', max_length=200)),
                ('inn', models.CharField(blank=True, help_text='B2B mijoz uchun STIR (e-faktura)', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='inventory_c_phone_cc89f4_idx')],
            },
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.customer'),
        ),
    ]
