# Generated by Django 6.0.5 on 2026-06-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_customer_saletransaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='line_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bu qatorga berilgan chegirma (so'm)", max_digits=12),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Chegirma sababi (audit uchun)', max_length=200),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Butun chek bo'yicha chegirma (so'm)", max_digits=12),
        ),
    ]
