# Generated by Django 6.0.5 on 2026-06-03 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sale_line_discount_saletransaction_discount_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, help_text="Smen boshida kassada bo'lgan pul (so'm)", max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Smen oxirida sanab chiqilgan naqd', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopilgan')], default='open', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='inventory.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smen',
                'verbose_name_plural': 'Smenlar',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Sotuv qaysi smen davomida amalga oshirilgan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.shift'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('branch',), name='one_open_shift_per_branch'),
        ),
    ]
