# Generated by Django 6.0.5 on 2026-06-03 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_transfer_transferline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Sanalmoqda'), ('applied', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='open', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes_applied', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='inventory.branch')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventarizatsiya',
                'verbose_name_plural': 'Inventarizatsiyalar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField(help_text='Inventarizatsiya boshlangandagi tizim miqdori (snapshot)')),
                ('counted_qty', models.IntegerField(help_text='Jismonan sanab chiqilgan miqdor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.stocktake')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant')),
            ],
            options={
                'ordering': ['variant__product__code', 'variant__size'],
                'unique_together': {('session', 'variant')},
            },
        ),
    ]
