# Generated by Django 6.0.5 on 2026-06-03 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktake_stocktakecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Mijoz ismi yoki belgi', max_length=80)),
                ('cart_json', models.TextField(help_text='Savat snapshoti (JSON)')),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('order_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_sales', to='inventory.branch')),
                ('parked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Park qilingan savat',
                'verbose_name_plural': 'Park qilingan savatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
