# Generated by Django 6.0.5 on 2026-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_parkedsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Ulgurji narx (1 dona, so'm). 0 bo'lsa chakana narx qo'llaniladi.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Chakana narx (1 dona, so'm)", max_digits=12),
        ),
    ]
