# Generated by Django 6.0.5 on 2026-06-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_branchstock_wholesale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sotuvchi komissiyasi (sotuv summasidan foiz). 0 = komissiyasiz.', max_digits=5),
        ),
    ]
