# Generated by Django 6.0.5 on 2026-06-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_user_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='monthly_other_costs',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Oylik boshqa qat'iy xarajatlar: ish haqi, kommunal, internet va h.k.", max_digits=14),
        ),
        migrations.AddField(
            model_name='branch',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Oylik ijara (so'm). Filial P&L hisobida qatnashadi.", max_digits=14),
        ),
    ]
