# Generated by Django 6.0.5 on 2026-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_branch_monthly_other_costs_branch_monthly_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='payment_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Mixed to'lov bo'lganda har turning summasi: [{method, amount}]"),
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('mixed', 'Aralash')], default='cash', help_text="Asosiy yoki yagona to'lov turi. Mixed bo'lsa payment_breakdown'da batafsil.", max_length=20),
        ),
    ]
