# Generated by Django 6.0.5 on 2026-06-03 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_saletransaction_payment_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('promo_type', models.CharField(choices=[('percent_off', 'Foiz chegirma'), ('buy_x_get_y', 'N olganga M bepul'), ('nth_percent_off', 'Har N-mahsulotga chegirma')], default='percent_off', max_length=30)),
                ('percent', models.DecimalField(decimal_places=2, default=0, help_text='Foiz chegirma (0-100). percent_off va nth_percent_off uchun.', max_digits=5)),
                ('qty_required', models.PositiveIntegerField(default=1, help_text="Buy-X-Get-Y'da X. Nth_percent'da N. percent_off'da min mahsulot soni.")),
                ('qty_free', models.PositiveIntegerField(default=0, help_text="Buy-X-Get-Y'da Y (eng arzonidan)")),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text="Bo'sh — muddatsiz", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text="Faqat shu kategoriyaga. Bo'sh — barcha mahsulotlar.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='inventory.category')),
                ('target_products', models.ManyToManyField(blank=True, help_text="Aniq mahsulotlar. Bo'sh va kategoriya bo'sh — barchasi.", related_name='promotions', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Aksiya',
                'verbose_name_plural': 'Aksiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
