# Generated by Django 6.0.5 on 2026-06-03 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank'), ('humo', 'Humo Pay'), ('anor', 'Anor (muddatli)'), ('alif', 'Alif (muddatli)'), ('iman', 'Iman (muddatli)'), ('zoodpay', 'Zoodpay (muddatli)'), ('other', 'Boshqa')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Ko\'rsatma: "Yetakchi hisob", "Qo\'shimcha karta" va h.k.', max_length=120)),
                ('qr_image', models.ImageField(blank=True, help_text="QR rasm fayli. Bo'sh bo'lsa qr_payload'dan generatsiya qilinadi.", null=True, upload_to='payment_qrs/')),
                ('qr_payload', models.CharField(blank=True, help_text="QR ichidagi matn/URL (masalan to'lov ilovasiga deeplink). qr_image bo'lmasa shu asosida QR generatsiya qilinadi.", max_length=500)),
                ('instructions', models.CharField(blank=True, help_text='Mijozga ko\'rsatma: "Summa: TOTAL so\'m" yoki maxsus izoh', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to='inventory.branch')),
            ],
            options={
                'verbose_name': "To'lov QR",
                'verbose_name_plural': "To'lov QR'lar",
                'ordering': ['branch', 'provider'],
            },
        ),
    ]
