# Generated by Django 6.0.5 on 2026-06-03 18:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_paymentqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='payme, click, uzum...', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ref_code', models.CharField(db_index=True, help_text="Mijoz to'lov izohi sifatida kiritadigan kod", max_length=12)),
                ('cart_snapshot', models.TextField(blank=True, help_text="POS savatining JSON snapshot'i — paid bo'lgach checkout uchun")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('cancelled', 'Bekor qilindi'), ('expired', 'Muddati tugadi')], db_index=True, default='pending', max_length=20)),
                ('provider_txn_id', models.CharField(blank=True, help_text='Provider tomonidan berilgan ID', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='inventory.branch')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents_initiated', to=settings.AUTH_USER_MODEL)),
                ('sale_transaction', models.OneToOneField(blank=True, help_text="Paid bo'lib checkout amalga oshgan bo'lsa, shu SaleTransaction", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='inventory.saletransaction')),
            ],
            options={
                'verbose_name': "To'lov niyati",
                'verbose_name_plural': "To'lov niyatlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
