# Generated by Django 6.0.5 on 2026-06-03 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_paymentintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, help_text='STIR (yuridik shaxs uchun)', max_length=14)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='is_return',
            field=models.BooleanField(default=False, help_text='Yetkazib beruvchiga qaytarish (quantity manfiy)'),
        ),
        migrations.AddField(
            model_name='intake',
            name='return_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='intake',
            name='quantity',
            field=models.IntegerField(help_text="Manfiy bo'lishi mumkin — yetkazib beruvchiga qaytarish"),
        ),
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_text', models.CharField(blank=True, help_text="Supplier model'da yo'q bo'lsa, erkin matn", max_length=200)),
                ('invoice_number', models.CharField(blank=True, help_text='Yetkazib beruvchining faktura raqami', max_length=80)),
                ('invoice_image', models.ImageField(blank=True, help_text='Faktura/dostavka fotografiyasi', null=True, upload_to='invoices/')),
                ('note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_sessions', to='inventory.branch')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_sessions', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Qabul sessiyasi',
                'verbose_name_plural': 'Qabul sessiyalari',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Bir partiyadagi bir nechta qabullarni guruhlash', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='inventory.intakesession'),
        ),
        migrations.AddField(
            model_name='intake',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, help_text="Yetkazib beruvchi (model). Eski yozuvlarda supplier matn'da.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='inventory.supplier'),
        ),
    ]
