# Generated by Django 6.0.5 on 2026-06-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_supplier_intake_is_return_intake_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='shift',
            field=models.ForeignKey(blank=True, help_text="Refund qaysi smen davomida amalga oshgan — kassa farqiga ta'sir", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='inventory.shift'),
        ),
    ]
