# Generated by Django 6.0.5 on 2026-06-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_return_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Ishlab chiqaruvchi tomonidan chop etilgan barcode (EAN-13, UPC va h.k.). Skanerlash uchun ishlatiladi.', max_length=64),
        ),
    ]
