# Generated by Django 6.0.5 on 2026-06-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_external_barcode_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Ishlab chiqaruvchi tomonidan chop etilgan barcode (EAN-13, UPC va h.k.). Skanerlash uchun ishlatiladi.', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at'], name='sale_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', '-sold_at'], name='sale_branch_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['variant', '-sold_at'], name='sale_variant_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_by', '-sold_at'], name='sale_seller_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['transaction', 'sold_at'], name='sale_txn_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['sold_at'], name='saletxn_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['branch', '-sold_at'], name='saletxn_branch_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['sold_by', '-sold_at'], name='saletxn_seller_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['payment_method', '-sold_at'], name='saletxn_pay_soldat_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['branch', '-opened_at'], name='shift_branch_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', '-opened_at'], name='shift_status_opened_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'dispatched_at'], name='transfer_status_disp_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['from_branch', 'status'], name='transfer_from_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_branch', 'status'], name='transfer_to_status_idx'),
        ),
    ]
