# Generated by Django 6.0.5 on 2026-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Turga xos shtrix-kod (EAN-13 va h.k.) — har tur uchun alohida.', max_length=64, null=True, unique=True),
        ),
    ]
