# Generated by Django 6.0.5 on 2026-07-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_productvariant_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, help_text='Brend nomi (masalan: Zara, Nike). Kiyim/poyabzal uchun ishlatiladi.', max_length=100),
        ),
    ]
