# Generated by Django 6.0.5 on 2026-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_open_price',
            field=models.BooleanField(default=False, help_text="Ochiq narx (qo'lda summa) — kiyim/poyabzalni tizimga kiritmasdan sotish uchun. Ombor tekshirilmaydi/kamaymaydi."),
        ),
    ]
