# Generated by Django 6.0.5 on 2026-07-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_product_is_open_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='bs_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='bs_sale_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='branchstock',
            constraint=models.CheckConstraint(condition=models.Q(('wholesale_price__gte', 0)), name='bs_wholesale_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='intake',
            constraint=models.CheckConstraint(condition=models.Q(('cost_per_unit__gte', 0)), name='intake_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('default_sale_price__gte', 0)), name='product_sale_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('markup_percent__gte', 0)), name='product_markup_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='sale_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('cost_at_sale__gte', 0)), name='sale_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('line_discount__gte', 0)), name='sale_linedisc_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='saletransaction',
            constraint=models.CheckConstraint(condition=models.Q(('order_discount__gte', 0)), name='saletxn_orderdisc_nonneg'),
        ),
    ]
