# Generated by Django 6.0.5 on 2026-07-16
from django.db import migrations, models


def zero_markup(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.update(markup_percent=0)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_user_recovery_codes_user_totp_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Foiz: sotuv narxi = tannarx × (1 + foiz/100)', max_digits=6),
        ),
        migrations.RunPython(zero_markup, noop),
    ]
