# Generated by Django 6.0.5 on 2026-07-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_quicksell_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Shu qabuldagi sotuv narxi. Eski yozuvlarda bo'sh.", max_digits=12, null=True),
        ),
    ]
