# Generated by Django 6.0.5 on 2026-07-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_seed_groups_classify'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pending_name',
            field=models.CharField(blank=True, default='', help_text='Nakladnoydan kelgan muqobil nom (tasdiqlanmagan).', max_length=200),
        ),
    ]
