# Generated by Django 6.0.5 on 2026-08-12 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_product_pending_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, help_text="Agar xodim ro'yxatda bo'lmasa — ismini yozing", max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Qarz summasi (so'm)", max_digits=12)),
                ('note', models.CharField(blank=True, help_text='Nima olindi / izoh', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_debts', to='inventory.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_debts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text="Qarz olgan xodim (ro'yxatdan)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Xodim qarzi',
                'verbose_name_plural': 'Xodim qarzlari',
                'ordering': ['is_paid', '-created_at'],
            },
        ),
    ]
