# Generated by Django 6.0.5 on 2026-08-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_employeedebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='cash_refunded',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Almashtirishда mijozga HAQIQIY qaytarilgan naqd (odatda 0 yoki faqat farq). None bo'lsa — oddiy qaytarish, refund_amount ishlatiladi.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='is_exchange',
            field=models.BooleanField(default=False, help_text='Bu qaytarish almashtirish qismimi (eski tovar yangisiga)'),
        ),
    ]
