# Generated by Django 6.0.5 on 2026-08-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_return_cash_refunded_return_is_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDebtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Tovar nomi (snapshot)', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.employeedebt')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_debt_items', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Xodim qarzi — tovar',
                'verbose_name_plural': 'Xodim qarzi — tovarlar',
            },
        ),
    ]
