# Generated by Django 6.0.5 on 2026-08-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_employeedebtitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedebt',
            name='paid_shift',
            field=models.ForeignKey(blank=True, help_text="Qarz qaysi smen davomida to'landi — kassaga naqd tushishi shu smenning kutilgan naqdiga qo'shiladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments', to='inventory.shift'),
        ),
    ]
