# Generated by Django 6.0.5 on 2026-08-25 22:04

from django.db import migrations, models


VALID = ['cash', 'card', 'transfer', 'mixed']


def normalize_payment_methods(apps, schema_editor):
    # Eski chek qatorlarida payment_method sifatida QR-provayder nomlari
    # ('payme', 'click', ...) saqlanib qolgan bo'lishi mumkin. Bular pulni
    # o'tkazma orqali oladi — 'transfer'ga normallashtiramiz, aks holda
    # CheckConstraint qo'shilmaydi.
    SaleTransaction = apps.get_model('inventory', 'SaleTransaction')
    SaleTransaction.objects.exclude(payment_method__in=VALID).update(
        payment_method='transfer')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_employeedebt_paid_shift'),
    ]

    operations = [
        migrations.RunPython(normalize_payment_methods, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='saletransaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['cash', 'card', 'transfer', 'mixed'])), name='saletxn_payment_method_valid'),
        ),
    ]
