# Generated by Django 6.0.5 on 2026-08-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_saletransaction_saletxn_payment_method_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Offline replay uchun bir martalik kalit (takroriy chekni bloklaydi)', max_length=64, null=True, unique=True),
        ),
    ]
