# Generated by Django 6.0.5 on 2026-08-26 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_saletransaction_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('damage', 'Shikastlangan'), ('loss', "Yo'qolgan"), ('spoilage', "Buzilgan / muddati o'tgan"), ('theft', "O'g'irlangan"), ('supplier_return', 'Yetkazuvchiga qaytarildi'), ('correction', 'Tuzatish (inventarizatsiya)'), ('other', 'Boshqa')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('cost_at_writeoff', models.DecimalField(decimal_places=2, default=0, help_text="Yozuv paytidagi tannarx (yo'qotish qiymatini hisoblash uchun)", max_digits=12)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='inventory.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Hisobdan chiqarish',
                'verbose_name_plural': 'Hisobdan chiqarishlar',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='writeoff_qty_positive')],
            },
        ),
    ]
