# Generated by Django 6.0.5 on 2026-08-26 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_stockwriteoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Kassaga qo'shilgan summa (so'm)", max_digits=12)),
                ('category', models.CharField(choices=[('float', 'Maydalik (float)'), ('owner', "Egasi qo'ydi"), ('correction', 'Tuzatish'), ('other', 'Boshqa')], default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ins', to='inventory.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ins', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ins', to='inventory.shift')),
            ],
            options={
                'verbose_name': 'Kassa kirimi',
                'verbose_name_plural': 'Kassa kirimlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', '-created_at'], name='cashin_branch_dt')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cashin_amount_positive')],
            },
        ),
    ]
