# Generated by Django 6.0.5 on 2026-08-26 09:23

import uuid
from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    # Mavjud cheklarга HAR BIRIGA alohida tasodifiy token beramiz (bitta
    # umumiy default hammasiga tushib qolmasin — aks holda token takrorlanardi).
    SaleTransaction = apps.get_model('inventory', 'SaleTransaction')
    rows = SaleTransaction.objects.all().only('id', 'public_id')
    batch = []
    for r in rows.iterator(chunk_size=2000):
        r.public_id = uuid.uuid4()
        batch.append(r)
        if len(batch) >= 2000:
            SaleTransaction.objects.bulk_update(batch, ['public_id'])
            batch = []
    if batch:
        SaleTransaction.objects.bulk_update(batch, ['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_cashin'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_public_ids, migrations.RunPython.noop),
    ]
