# Generated by Django 6.0.5 on 2026-08-26 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_saletransaction_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Foiz chegirma (0-100). percent_off va nth_percent_off uchun.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sotuvchi komissiyasi (sotuv summasidan foiz, 0-100). 0 = komissiyasiz.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('cash_refunded__isnull', True), ('cash_refunded__gte', 0), _connector='OR'), name='return_cash_refunded_nonneg'),
        ),
    ]
