# Generated by Django 6.0.5 on 2026-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_alter_promotion_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='closing_expected_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yopilish paytida hisoblangan kutilgan naqd (qotirilgan)', max_digits=12, null=True),
        ),
    ]
