# Generated by Django 6.0.5 on 2026-08-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_shift_closing_expected_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='inventory.productvariant'),
        ),
    ]
