# Generated by Django 6.0.8 on 2026-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_idempotency_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, help_text='Takroriy qaytarishni bloklovchi bir martalik kalit', max_length=64, null=True, unique=True),
        ),
    ]
