# Generated by Django 6.0.8 on 2026-08-27 10:02

from django.db import migrations, models

EXCHANGE_PREFIX = 'Almashtirish'


def backfill(apps, schema_editor):
    """DISC-1: eski cheklarni bor ma'lumot darajasida taqsimlaymiz.

    `discount_reason` yagona ishonchli belgi:
      - 'Almashtirish...'  -> butun summa ALMASHTIRISH krediti (pos_exchange
        aynan shu sababni yozadi);
      - sabab BO'SH        -> butun summa AKSIYA. Chunki pos_checkout qo'lda
        chegirma uchun sababni MAJBURIY qiladi (sababsiz qo'lda chegirma
        umuman saqlanmagan), demak sababsiz summa faqat serverning aksiya
        hisobidan kelgan;
      - sabab BOR (almashtirish emas) -> QO'LDA (ikkalasi ham nol qoladi).
        Aksiya + qo'lda aralash chek bo'lsa, tarixda ular bitta songa
        qo'shilib ketgan — ajratib bo'lmaydi, shuning uchun butunlay qo'lda
        deb qoldiramiz (kam sonli va kichik summa; YANGI cheklar aniq).
    """
    Txn = apps.get_model('inventory', 'SaleTransaction')
    Txn.objects.filter(order_discount__gt=0,
                       discount_reason__startswith=EXCHANGE_PREFIX
                       ).update(exchange_credit=models.F('order_discount'))
    Txn.objects.filter(order_discount__gt=0, discount_reason=''
                       ).update(promo_discount=models.F('order_discount'))


def unbackfill(apps, schema_editor):
    Txn = apps.get_model('inventory', 'SaleTransaction')
    Txn.objects.update(promo_discount=0, exchange_credit=0)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0059_return_refund_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="saletransaction",
            name="exchange_credit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="order_discount ichidagi ALMASHTIRISH krediti — eski tovar qiymati. Chegirma emas: mijoz shu qismni tovar bilan to'lagan.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="saletransaction",
            name="promo_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="order_discount ichidagi AKSIYA ulushi (server hisoblaydi)",
                max_digits=12,
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
        migrations.AddConstraint(
            model_name="saletransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("promo_discount__gte", 0)),
                name="saletxn_promodisc_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="saletransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("exchange_credit__gte", 0)),
                name="saletxn_exchcredit_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="saletransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("promo_discount__lte", models.F("order_discount"))),
                name="saletxn_promodisc_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="saletransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exchange_credit__lte", models.F("order_discount"))
                ),
                name="saletxn_exchcredit_lte_total",
            ),
        ),
    ]
