# Generated by Django 6.0.8 on 2026-08-29 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0061_fix_promo_backfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Brauzerda saqlanadigan tasodifiy ID (localStorage)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Egasi qo'ygan nom, masalan 'Kassa 1'",
                        max_length=60,
                    ),
                ),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                (
                    "catalog_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Qurilmada saqlangan tovar soni"
                    ),
                ),
                (
                    "catalog_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Katalog oxirgi marta yangilangan vaqt",
                        null=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_devices",
                        to="inventory.branch",
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kassa qurilmasi",
                "verbose_name_plural": "Kassa qurilmalari",
                "ordering": ["-last_seen"],
            },
        ),
    ]
