# Generated by Django 6.0.8 on 2026-08-29 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0062_pos_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        help_text="Ishlovchi nomi (jobs.HANDLERS kaliti)",
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Navbatda"),
                            ("running", "Bajarilmoqda"),
                            ("done", "Bajarildi"),
                            ("failed", "Xato"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("last_error", models.TextField(blank=True)),
                (
                    "run_after",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Shu vaqtdan oldin olinmaydi (qayta urinish)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Fon ishi",
                "verbose_name_plural": "Fon ishlari",
                "ordering": ["run_after", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "run_after"], name="bgjob_status_runafter"
                    )
                ],
            },
        ),
    ]
