# -*- coding: utf-8 -*-
"""AI intake qoralamasi — 28.08.2026 nakladnoyi (BOZ NURMETOVA NAZOKAT).

Rasm sifatida emas, TAYYOR jadval sifatida yuklanadi. Qoralama omborga
TA'SIR QILMAYDI — /intake/photo/ da ochib tekshirasiz, keyin qabul qilasiz.
"""
import json
from inventory.models import InvoiceDraft, Branch
from django.contrib.auth import get_user_model

PAYLOAD = json.loads(r'''{
 "branch": "",
 "supplier": "БОЗ НУРМЕТОВА НАЗОКАТ (ДАВРОН)",
 "agent": "АБДУЛЛАЕВ ИНОЯТ",
 "agent_phone": "+998 93 740-20-90",
 "invoice_no": "02793",
 "date": "28.08.2026",
 "marja": "",
 "total": "11282721.2",
 "rows": [
  {
   "name": "Део LSS - Стик - Inv Dry Shower Fresh 40gr /12",
   "product": "Део LSS - Стик - Inv Dry Shower Fresh 40gr /12",
   "type": "",
   "size": "",
   "barcode": "61016769",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS Stick 24/7 Fresh Fusion 45gr/12",
   "product": "Део LSS Stick 24/7 Fresh Fusion 45gr/12",
   "type": "",
   "size": "",
   "barcode": "61016755",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS Stick ID Pure Freshness 45gr/12",
   "product": "Део LSS Stick ID Pure Freshness 45gr/12",
   "type": "",
   "size": "",
   "barcode": "61016764",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS GEL Aloe Protection 65gr/12",
   "product": "Део LSS GEL Aloe Protection 65gr/12",
   "type": "",
   "size": "",
   "barcode": "61024592",
   "qty": "12",
   "cost": "29954.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "359448",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS GEL Inv Shower Fresh 65gr/12",
   "product": "Део LSS GEL Inv Shower Fresh 65gr/12",
   "type": "",
   "size": "",
   "barcode": "61041798",
   "qty": "12",
   "cost": "29954.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "359448",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део MSS Stick 24/7 Fresh Rush 50gr/12",
   "product": "Део MSS Stick 24/7 Fresh Rush 50gr/12",
   "type": "",
   "size": "",
   "barcode": "61016847",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део MSS Stick 24/7 Cool Fusion 50gr/12",
   "product": "Део MSS Stick 24/7 Cool Fusion 50gr/12",
   "type": "",
   "size": "",
   "barcode": "US06097A",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS - Спрэй - Unique Spray /12",
   "product": "Део LSS - Спрэй - Unique Spray /12",
   "type": "",
   "size": "",
   "barcode": "61021551",
   "qty": "12",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "325156",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS - Спрэй - Алоэ защита /12",
   "product": "Део LSS - Спрэй - Алоэ защита /12",
   "type": "",
   "size": "",
   "barcode": "RU00222A",
   "qty": "12",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "325156",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS - Спрэй - Антибактериальный эффект /12",
   "product": "Део LSS - Спрэй - Антибактериальный эффект /12",
   "type": "",
   "size": "",
   "barcode": "RU00392A",
   "qty": "12",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "325156",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Део LSS - Стик - Алоэ защита /12",
   "product": "Део LSS - Стик - Алоэ защита /12",
   "type": "",
   "size": "",
   "barcode": "FUS365537",
   "qty": "12",
   "cost": "21049.4",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "252593",
   "qty_note": "1 крб",
   "hint": "kod aniq emas"
  },
  {
   "name": "Део MSS - Спрэй - Feel Attractive 150мл /12",
   "product": "Део MSS - Спрэй - Feel Attractive 150мл /12",
   "type": "",
   "size": "",
   "barcode": "61051752",
   "qty": "6",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "162578",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "Део MSS - Спрэй - Feel Free 150мл /12",
   "product": "Део MSS - Спрэй - Feel Free 150мл /12",
   "type": "",
   "size": "",
   "barcode": "61024491",
   "qty": "6",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "162578",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "Део MSS - Спрэй - Neutro Power /12",
   "product": "Део MSS - Спрэй - Neutro Power /12",
   "type": "",
   "size": "",
   "barcode": "61021552",
   "qty": "6",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "162578",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "Део MSS - Спрэй - Невидимая защита /12",
   "product": "Део MSS - Спрэй - Невидимая защита /12",
   "type": "",
   "size": "",
   "barcode": "RU00617A",
   "qty": "6",
   "cost": "27096.3",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "162578",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Витамин В и Гранат /72",
   "product": "Мыло PO 150 гр - Витамин В и Гранат /72",
   "type": "",
   "size": "",
   "barcode": "61034836",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Витамин С и Апельсин /72",
   "product": "Мыло PO 150 гр - Витамин С и Апельсин /72",
   "type": "",
   "size": "",
   "barcode": "61056391",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "product": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "type": "",
   "size": "",
   "barcode": "61034986",
   "qty": "10",
   "cost": "0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "0",
   "qty_note": "10 шт",
   "hint": "BEPUL — narx 0"
  },
  {
   "name": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "product": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "type": "",
   "size": "",
   "barcode": "61034986",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "product": "Мыло PO 150 гр - Зеленый чай и огурец /72",
   "type": "",
   "size": "",
   "barcode": "61034986",
   "qty": "10",
   "cost": "0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "0",
   "qty_note": "10 шт",
   "hint": "BEPUL — narx 0"
  },
  {
   "name": "Мыло PO 150 гр - Малина и Пион /72",
   "product": "Мыло PO 150 гр - Малина и Пион /72",
   "type": "",
   "size": "",
   "barcode": "61044823",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Цитрус и крем /72",
   "product": "Мыло PO 150 гр - Цитрус и крем /72",
   "type": "",
   "size": "",
   "barcode": "61034983",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 150 гр - Massage /72",
   "product": "Мыло PO 150 гр - Massage /72",
   "type": "",
   "size": "",
   "barcode": "61046343",
   "qty": "24",
   "cost": "11654.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "279696",
   "qty_note": "24 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 5x70 гр - МЛ 4+1 Зеленый чай и огурец /24",
   "product": "Мыло PO 5x70 гр - МЛ 4+1 Зеленый чай и огурец /24",
   "type": "",
   "size": "",
   "barcode": "61032949",
   "qty": "12",
   "cost": "23447.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "281364",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 5x70 гр - МЛ 4+1 Олива /24",
   "product": "Мыло PO 5x70 гр - МЛ 4+1 Олива /24",
   "type": "",
   "size": "",
   "barcode": "61032948",
   "qty": "12",
   "cost": "23447.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "281364",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 5x70 гр - МЛ 4+1 Роза /24",
   "product": "Мыло PO 5x70 гр - МЛ 4+1 Роза /24",
   "type": "",
   "size": "",
   "barcode": "61032947",
   "qty": "12",
   "cost": "23447.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "281364",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 6x150 гр - МЛ - Олива /12",
   "product": "Мыло PO 6x150 гр - МЛ - Олива /12",
   "type": "",
   "size": "",
   "barcode": "61055770",
   "qty": "12",
   "cost": "63601.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "763212",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "Мыло PO 6x150 гр - МЛ - Роза /12",
   "product": "Мыло PO 6x150 гр - МЛ - Роза /12",
   "type": "",
   "size": "",
   "barcode": "61055772",
   "qty": "6",
   "cost": "63601.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "381606",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "Мыло PO 6x150 гр - МЛ - Ромашка и витамин Е /12",
   "product": "Мыло PO 6x150 гр - МЛ - Ромашка и витамин Е /12",
   "type": "",
   "size": "",
   "barcode": "61055771",
   "qty": "6",
   "cost": "63601.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "381606",
   "qty_note": "6 шт",
   "hint": ""
  },
  {
   "name": "ЗЩ Детская - от 2 и выше /72",
   "product": "ЗЩ Детская - от 2 и выше /72",
   "type": "",
   "size": "",
   "barcode": "VN01038A",
   "qty": "12",
   "cost": "8991.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "107892",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "ЗЩ Детская - от 2 и выше 2+1",
   "product": "ЗЩ Детская - от 2 и выше 2+1",
   "type": "",
   "size": "",
   "barcode": "61031445",
   "qty": "12",
   "cost": "17981.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "215772",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "ЗЩ ЗигЗаг - Gum Care soft /72",
   "product": "ЗЩ ЗигЗаг - Gum Care soft /72",
   "type": "",
   "size": "",
   "barcode": "61057210",
   "qty": "72",
   "cost": "11076.8",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "797530",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "ЗЩ ЗигЗаг - Древесный /72",
   "product": "ЗЩ ЗигЗаг - Древесный /72",
   "type": "",
   "size": "",
   "barcode": "61057209",
   "qty": "72",
   "cost": "11076.8",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "797530",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "ЗЩ ЗигЗаг - Древесный уголь 2+1 /48",
   "product": "ЗЩ ЗигЗаг - Древесный уголь 2+1 /48",
   "type": "",
   "size": "",
   "barcode": "61057325",
   "qty": "12",
   "cost": "24426.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "293112",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "ЗЩ Классика здоровья 2+1",
   "product": "ЗЩ Классика здоровья 2+1",
   "type": "",
   "size": "",
   "barcode": "FVN50306",
   "qty": "72",
   "cost": "5568.8",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "400951",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "ЗЩ Классика здоровья /48",
   "product": "ЗЩ Классика здоровья /48",
   "type": "",
   "size": "",
   "barcode": "VN01318A",
   "qty": "48",
   "cost": "11134.8",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "534468",
   "qty_note": "1 крб",
   "hint": ""
  },
  {
   "name": "ЗП 50 мл (66 гр) - Детская - 1+1",
   "product": "ЗП 50 мл (66 гр) - Детская - 1+1",
   "type": "",
   "size": "",
   "barcode": "61056059",
   "qty": "12",
   "cost": "15360.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "184320",
   "qty_note": "12 шт",
   "hint": ""
  },
  {
   "name": "ЗП Доктор Заяц Str+Bub Bipack",
   "product": "ЗП Доктор Заяц Str+Bub Bipack",
   "type": "",
   "size": "",
   "barcode": "",
   "qty": "2",
   "cost": "7505.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "15010",
   "qty_note": "2 шт",
   "hint": "KOD O'QILMADI"
  },
  {
   "name": "ЗП 50 мл (73 гр) - Тройное действие /72",
   "product": "ЗП 50 мл (73 гр) - Тройное действие /72",
   "type": "",
   "size": "",
   "barcode": "61031421",
   "qty": "2",
   "cost": "13607.0",
   "marja": "",
   "sale": "",
   "category": "",
   "line_sum": "27214",
   "qty_note": "2 шт",
   "hint": ""
  }
 ]
}''')

U = get_user_model()
user = (U.objects.filter(username='admin').first()
        or U.objects.filter(is_superuser=True).first()
        or U.objects.filter(is_staff=True).first())
if user is None:
    raise SystemExit('XATO: admin foydalanuvchi topilmadi.')

br = Branch.objects.filter(is_active=True).order_by('id').first()
if br:
    PAYLOAD['branch'] = str(br.pk)

d = InvoiceDraft.objects.create(
    created_by=user, branch=br,
    supplier_text=PAYLOAD['supplier'],
    invoice_number=PAYLOAD['invoice_no'],
    payload=PAYLOAD,
)
print()
print(f"Qoralama #{d.pk} yaratildi")
print(f"  taminotchi : {d.supplier_text}")
print(f"  filial     : {br.name if br else '(yoq)'}")
print(f"  egasi      : {user.username}")
print(f"  qatorlar   : {d.row_count}")
print(f"  dona jami  : {d.total_qty}")
print(f"  chek Итого : {PAYLOAD['total']}")
print()
print(f"  ochish: https://koreysbozor.uz/intake/photo/?draft={d.pk}")
print()
